### ISSUE TITLE
Where to put the "point_cloud.ply" file?

### ISSUE THREAD

**Issue by kevinloustau** [haztro/godot-gaussian-splatting#1]
Hi @haztro,

Thank you for working on the implementation of Gaussian splat in Godot !
I tried the project, but I am not sure where we should put the **point_cloud.ply** file in the project?

**Comment by haztro** [comment]
heya, thanks for checking it out! ah, my bad, it needs to go in the godot project directory (where the godot "project" file is located).

**Comment by kevinloustau** [comment]
Thanks for the indication! 
Unfortunately, when I launch the scene the window closes after a few seconds, and I don't have any error. 

This is the file I use: [point_cloud.zip](https://github.com/haztro/godot-splat/files/13818451/point_cloud.zip)

**Comment by haztro** [comment]
I'm assuming you've unzipped the file and are using "point_cloud.ply" - the app expects "point_cloud.ply". Looking at the file you've attached, I'm not certain the app will be able to correctly parse the header. I've only tested with a specific .ply header which looks like this: 

ply
format binary_little_endian 1.0
element vertex 1450458
property float x
property float y
property float z
property float nx
property float ny
property float nz
property float f_dc_0
property float f_dc_1
property float f_dc_2
property float f_rest_0
property float f_rest_1
property float f_rest_2
property float f_rest_3
property float f_rest_4
property float f_rest_5
property float f_rest_6
property float f_rest_7
property float f_rest_8
property float f_rest_9
property float f_rest_10
property float f_rest_11
property float f_rest_12
property float f_rest_13
property float f_rest_14
property float f_rest_15
property float f_rest_16
property float f_rest_17
property float f_rest_18
property float f_rest_19
property float f_rest_20
property float f_rest_21
property float f_rest_22
property float f_rest_23
property float f_rest_24
property float f_rest_25
property float f_rest_26
property float f_rest_27
property float f_rest_28
property float f_rest_29
property float f_rest_30
property float f_rest_31
property float f_rest_32
property float f_rest_33
property float f_rest_34
property float f_rest_35
property float f_rest_36
property float f_rest_37
property float f_rest_38
property float f_rest_39
property float f_rest_40
property float f_rest_41
property float f_rest_42
property float f_rest_43
property float f_rest_44
property float opacity
property float scale_0
property float scale_1
property float scale_2
property float rot_0
property float rot_1
property float rot_2
property float rot_3
end_header

With the number following "element vertex" being the number of vertices. Since your file doesn't follow this format, I can't say whether or not it will work (perhaps in the future i'll look into supporting alternative headers). I had a quick look and it seems the models offered on [poly.cam](https://poly.cam/) follow the above format. I've also only tested on windows! 

For more error messages, try running the console version of godot (if on windows) or running godot from a terminal (if on macos) - there'll be some additional debug output in the terminal. 

Sorry i can't be more helpful! I'd suggest trying some of the .ply files that have the above header - let me know how it goes. When I'm back at my windows machine I can try your attached file myself :)
