### ISSUE TITLE
Loading time  

### ISSUE THREAD

**Issue by rhohndorf** [haztro/godot-gaussian-splatting#3]
![Screenshot from 2024-06-04 01-08-50](https://github.com/haztro/godot-gaussian-splatting/assets/7142918/266fad5e-ec7c-435d-b13b-0210fcabbb3a)
I am on Ubuntu 22.04 and Godot 4.2.2 with forward renderer selected. I changed the path to the ply file to point at a small file (2.5MB, ~50000 splats). Then I hit the play button. In other viewers this file is loaded in seconds. It has no spherical harmonics.
As you can see from the screenshot, the file has been found and seems to have loaded successfully as far as I can tell. But the screen stays black and all cpu cores are at 100% for several minutes now, while the gpu is more or less idleing.

What am I missing ?

**Comment by haztro** [comment]
sorry about that, I haven't tested on ubuntu nor with any files with no spherical harmonics. The .ply loading is super basic and has only been tested on the demo splats from the original paper. Could you post the header of the .ply file?

**Comment by rhohndorf** [comment]
Ah yes, I had a quick look at the ply loading function in the gdscript.
There's not really a standard what has to go into the ply or how many spherical harmonics to use. Different tools produce different output. 
From what i've seen in the wild these are mandatory (otherwise GS won't work):
property float x
property float y 
property float z 
property float f_dc_0 
property float f_dc_1 
property float f_dc_2 
property float opacity 
property float scale_0 
property float scale_1 
property float scale_2 
property float rot_0
property float rot_1 
property float rot_2 
property float rot_3

The rest is optional. The loading function probably needs to read the ply header first and then analyze what's there. 

I will check with one of the demo scenes asap to verify that everything works though.

**Comment by haztro** [comment]
yea, loading is definitely something that still needs work. For now, you could adjust the loading by removing the normals (nx,ny,nz) and spherical coords (f_rest_n): 

"x": file.get_float(),
"y": file.get_float(),
"z": file.get_float(),
"f_dc_0": file.get_float(),
"f_dc_1": file.get_float(),
"f_dc_2": file.get_float(),
"opacity": file.get_float(),
"scale_0": file.get_float(),
"scale_1": file.get_float(),
"scale_2": file.get_float(),
"rot_0": file.get_float(),
"rot_1": file.get_float(),
"rot_2": file.get_float(),
"rot_3": file.get_float()

You would also need to set sh_degree to 0 (declared globally at top of main.gd). This will still give issues since in the splat.glsl shader:

vec3 sh[16];
for (int i = 0; i < 48; i += 3) {
    sh[i] = vec3(coeffs[idx * 48 + i], coeffs[idx * 48 + i + 1], coeffs[idx * 48 + i + 2]);
}

It's expecting 16 vec3s per splat. You could try changing this to:

vec3 sh[1];
for (int i = 0; i < 3; i += 3) {
    sh[i] = vec3(coeffs[idx * 3 + i], coeffs[idx * 3 + i + 1], coeffs[idx * 3 + i + 2]);
}

I can't test the above at the moment but something similar should hopefully get your file working.

**Comment by rhohndorf** [comment]
Hmm. unfortunately it's not working for me with the bicycle scene as well. The debug window stays black and nothing seems to happen.

Here's the header:
ply
format binary_little_endian 1.0
element vertex 6131954
property float x
property float y
property float z
property float nx
property float ny
property float nz
property float f_dc_0
property float f_dc_1
property float f_dc_2
property float f_rest_0
property float f_rest_1
property float f_rest_2
property float f_rest_3
property float f_rest_4
property float f_rest_5
property float f_rest_6
property float f_rest_7
property float f_rest_8
property float f_rest_9
property float f_rest_10
property float f_rest_11
property float f_rest_12
property float f_rest_13
property float f_rest_14
property float f_rest_15
property float f_rest_16
property float f_rest_17
property float f_rest_18
property float f_rest_19
property float f_rest_20
property float f_rest_21
property float f_rest_22
property float f_rest_23
property float f_rest_24
property float f_rest_25
property float f_rest_26
property float f_rest_27
property float f_rest_28
property float f_rest_29
property float f_rest_30
property float f_rest_31
property float f_rest_32
property float f_rest_33
property float f_rest_34
property float f_rest_35
property float f_rest_36
property float f_rest_37
property float f_rest_38
property float f_rest_39
property float f_rest_40
property float f_rest_41
property float f_rest_42
property float f_rest_43
property float f_rest_44
property float opacity
property float scale_0
property float scale_1
property float scale_2
property float rot_0
property float rot_1
property float rot_2
property float rot_3
end_header

This all looks correct. So I think there must be something else going on.
I get these error messages:
![image](https://github.com/haztro/godot-gaussian-splatting/assets/7142918/d4f35dfd-70b4-4922-9e8a-68d69f7b1761)

**Comment by haztro** [comment]
okay, i've actually noticed a bug in the code I just posted - there's an indexing error (should be sh[i/3] not sh[i]). No idea how this worked at all on my machine. I've pushed the changes and it works on my mac now (before it only worked on my windows comp and i wasn't sure why). See if this helps?

**Comment by rhohndorf** [comment]
Thanks, rendering is working now for the bicycle scene. Rendering speed is absolutely glacial though. Am I correct that turning the mouse wheel should rotate the camera. Does not happen for me at all.

**Comment by haztro** [comment]
Mouse wheel will scale the splats, right clicking (and holding) will rotate the camera. yea, it can be quite slow. I haven't implemented the culling algorithm they use in the original paper - I suspect this would provide some speed up. I also compute the cov3d matrix at runtime rather than precompute it (i'll get around to this at some point) like most implementations do. The other bottleneck is likely the depth sorting. I'd like to get it to the point that it's comparable to other online viewers but for now it's more of a proof of concept (that it can work in godot).

**Comment by rhohndorf** [comment]
Ah okay I see. Rotating works but yea, I get something like 1 frame every 5-10 seconds on this 6 million splats scene with an rtx3090. Is it possible the sorting takes so long in gdscript ? I've looked at this webGL viewer a while ago. https://github.com/antimatter15/splat/blob/main/main.js
As far as I can tell it's not using any fancy culling, but the rendering speed is significantly higher. The sorting in this case is done in a separate web worker on the CPU. Also not ideal, but works reasonably well. 
Unfortunately I'm new to Godot, so I have no idea how to debug this on my end. Is there something like a flame graph, so I can see where the script spends most of its time? 
Also, and i'm completely talking out of my ass here, would it make sense to use a built-in sorting function as it would be implemented in C++ instead of GDScript ?

**Comment by haztro** [comment]
godot has the profiler you could check out:
![image](https://github.com/haztro/godot-gaussian-splatting/assets/47906140/fd1b89ff-227b-4728-8713-53e15b6facbe)

That was my first thought too. I tried using godot's in-built sort but I think since you need a custom sort function (distance from camera to splat) it slows things down - it ended up being way slower which is why i ended up implementing gpu sort. It could be worth just writing everything in c++ as a [gdextension](https://docs.godotengine.org/en/stable/tutorials/scripting/gdextension/gdextension_cpp_example.html)

I'll try precomputing the cov3d matrix and see how much that helps.
